### ISSUE TITLE
How to exclude this object?

### ISSUE THREAD

**Issue by kettenbach-it** [bpineau/katafygio#116]
Hi!

I'm wondering how to exclude this object? It changes every minute and causes a lot of unnecessary commits. I can't use kind since I want to backup all other ClusterRoles

![image](https://user-images.githubusercontent.com/7711872/128190112-4501fe31-9f06-44f8-aa78-e001c7451a1f.png)

**Comment by bpineau** [comment]
Hi, have you tried `--exclude-object clusterrole:system:master-monitoring-role` ?

**Comment by kettenbach-it** [comment]
Thanks! I must have overlooked this option.
