### ISSUE TITLE
Helm chart doesn't map PVC

### ISSUE THREAD

**Issue by greenaar** [bpineau/katafygio#68]
The helm chart offers a persistence option which isn't actually used. The PVC is created successfully, but not mapped to the pod.  As a result each re-deploy of a pod requires a fresh checkout.

Initially this is a quick process, but over time this will exceed the health check timeout (which is set too low and not exposed as a configuration value), causing the pod to continuously fail and retry.

Health check timeout should be exposed as an optional variable, and the persistent volume should be properly mapped.  The combination of these two items will successfully resolve this issue.

**Comment by bpineau** [comment]
Thanks for reporting !

Are you talking about the helm chart from [helm repositories](https://github.com/helm/charts/tree/master/stable/katafygio), or the one in in this repos (`assets/helm-chart/katafygio/`) ? I just fixed an issue wrt to volumes on the later. At least, I re-tested using a volume here and seen no issue (no AZ locality constraints on my test setup though).

Also just modified the local chart to expose tunables for liveness and readiness probes' delays (I suspect you need to tweak the liveness' `initialDelaySeconds`).

**Comment by greenaar** [comment]
Sorry for the delay responding, I mean the one in the helm repositories.  Thanks for exposing those additional values.

**Comment by bpineau** [comment]
Thanks, I'll re-test and submit the new delays options, and possible fixes to helm repos soon (trying to batch other modifications).

**Comment by greenaar** [comment]
An update - I've tried the helm chart you have in this repo, and i'm afraid it also doesn't seem to map the PVC.  It creates it, but the pod shows it bound, and shelling into the pod, I don't see it mounted.

![image](https://user-images.githubusercontent.com/249029/53277515-1e7f0000-36b9-11e9-8f32-99315fc979b2.png)

        "volumeMounts": [
          {
            "name": "katafygio-token-pdflc",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],

^^ the above is the only volume mount shown.

**Comment by greenaar** [comment]
More information.. I see the volume in the deployment and in the replica set, but not in the pod.

          {
            "name": "katafygio-data",
            "persistentVolumeClaim": {
              "claimName": "katafygio"
            }
          }

**Comment by tchellomello** [comment]
Hitting the same problem

**Comment by tchellomello** [comment]
@greenaar  I've fixed the issue and published the changes at https://github.com/helm/charts/compare/master...tchellomello:katafygio_mount_pvc 

I'll submit a PR to the stable/helm tree. Please let me know if that works for you.

**Comment by bpineau** [comment]
Oh :facepalm:.. great call @tchellomello, thanks!
I backported your change to the local chart (also with an useful related change: setting .spec.strategy.type==Recreate so the PV is released before a new pod starts, useful for rollouts).
