### ISSUE TITLE
Daemon don't pull GIT repository before commit

### ISSUE THREAD

**Issue by Dragonn** [bpineau/katafygio#72]
I am running katafygio version 0.7.3 in container from docker-hub (slightly modified container and almost sample config file).

When I am running katafygio and make single push into GIT repository manually (e.g. add README.md in my case), daemon stops backing up and only solution is to purge working dir (or recreate container in my case).

Daemon is just printing errors about unable to push because there is another commit in remote master (reformated for better reading):
```
failed to git push: git push failed with code exit status 1:
To gitlab.<redacted>:k8s-config-backup.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@gitlab.<redacted>:k8s-config-backup.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I suppose this can be relative easily fixed by pulling repository before commiting with ```git pull -s recursive -X ours``` to automaticaly resolve possible conflicts.

**Comment by Dragonn** [comment]
Okay, i dived into code and tried to fix this. Please check my changes, merging will be appreciated. Thx

**Comment by bpineau** [comment]
Closing, as your PR #73 fixed this (thanks!).
