### ISSUE TITLE
Publish Helm Chart

### ISSUE THREAD

**Issue by m4rcu5** [bpineau/katafygio#96]
Hi,

I see you maintain a Helm Chart in this project, but this is not the same one as published on the Helm Hub (https://hub.helm.sh/charts/stable/katafygio).
Your version also seems to support more features.

Would you like to publish your version to the Helm Hub to make installation easier for users. Especially for tools like K3s' build in Helm implementation, which sources from hosted charts.
Or is your version also hosted on a Chart repository?

Meanwhile I noticed that the version on Helm Hub was broken and I submitted a patch (https://github.com/helm/charts/pull/22494). However I think it would be nicer to have a version of the upstream maintainer there instead.

**Comment by bpineau** [comment]
Hi,
We'll have to setup our own Helm repository somehow, since Helm Hub is now deprecated and frozen.
Perhaps by setting up the helm Github Actions to publish with github (https://github.com/helm/charts-repo-actions-demo).
